updates

diff --git a/testsuite/makefile b/testsuite/makefile
--- a/testsuite/makefile
+++ b/testsuite/makefile
@@ -23,7 +23,7 @@ LOG := > /dev/null 2>&1
 #LOG := >> testsuite.log 2>&1
 
 
-all: start main1_a main1_b main2_a main2_b main3_a main3_b main4_a main4_b main5_a main5_b main6_a main6_b main17_a main17_b main24_a main24_b main25_a main25_b main28_a main28_b main29_a main29_b
+all: start main1_a main1_b main2_a main2_b main3_a main3_b main4_a main4_b main5_a main5_b main6_a main6_b main17_a main17_b test_20_a main24_a main24_b main25_a main25_b main28_a main28_b main29_a main29_b
 
 start:
 	echo "compile_assert() testsuite"
@@ -149,6 +149,15 @@ main17_a:
 		echo "main17_a: *FAIL*"; \
 	else \
 		echo "main17_a: PASS"; \
+	fi
+
+# should fail
+test_20_a:
+	$(CXX) $(INC_DIRS) $(FLAGS) -o test_20_a.bin test_20_a.cpp $(LOG); \
+	if [ $$? -eq 0 ]; then \
+		echo "test_20_a: *FAIL*"; \
+	else \
+		echo "test_20_a: PASS"; \
 	fi
 
 # should compile
@@ -281,3 +290,4 @@ main29_b:
 
 clean:
 	rm -f *.bin
+	rm -f *.o
