Add test_34_strlen and update strcpy test 33 to work again

diff --git a/testsuite/makefile b/testsuite/makefile
--- a/testsuite/makefile
+++ b/testsuite/makefile
@@ -17,7 +17,7 @@ INC_DIRS := -I..
 
 # clang does not support -ftrack-macro-expansion=0
 #clang uses  -fmacro-backtrace-limit=1
-FLAGS := $(INC_DIRS) -Wall -Werror -D__ENABLE_COMPILE_ASSERT__ -O2
+FLAGS := $(INC_DIRS) -Wall -Werror -D__ENABLE_COMPILE_ASSERT__ -O2 -ftrack-macro-expansion=0
 
 # Stop compiler outputting text, then only the return code is checked
 LOG := > /dev/null 2>&1
@@ -27,7 +27,7 @@ LOG := > /dev/null 2>&1
 
 # test_31_const_p_a test_31_const_p_b test_32_div_zero_a test_32_div_zero_b
 
-all: start main1_a main1_b main2_a main2_b main3_a main3_b main4_a main4_b main5_a main5_b main6_a main6_b main17_a main17_b test_20_a main24_a main24_b main25_a main25_b main28_a main28_b main29_a main29_b test_30_web_a test_30_web_b test_33_strcpy_a test_33_strcpy_b
+all: start main1_a main1_b main2_a main2_b main3_a main3_b main4_a main4_b main5_a main5_b main6_a main6_b main17_a main17_b test_20_a main24_a main24_b main25_a main25_b main28_a main28_b main29_a main29_b test_30_web_a test_30_web_b test_33_strcpy_a test_33_strcpy_b test_34_strlen_b
 
 start:
 	echo "compile_assert() testsuite"
@@ -352,7 +352,7 @@ test_32_div_zero_b:
 
 # should *not* compile
 test_33_strcpy_a:
-	$(CC) $(INC_DIRS) $(FLAGS) -Wno-div-by-zero -o test_33_strcpy_a.bin test_33_strcpy_a.c $(LOG); \
+	$(CC) $(INC_DIRS) $(FLAGS) -o test_33_strcpy_a.bin test_33_strcpy_a.c $(LOG); \
 	if [ $$? -eq 0 ]; then \
 		echo "test_33_strcpy_a: *FAIL*"; \
 	else \
@@ -360,13 +360,22 @@ test_33_strcpy_a:
 	fi
 
 
-# should compile
+# Unfortunately this compiles, due to lack of -fno-delete-null-pointer-checks
 test_33_strcpy_b:
-	$(CC) $(INC_DIRS) $(FLAGS) -Wno-div-by-zero -o test_33_strcpy_b.bin test_33_strcpy_b.c $(LOG); \
+	$(CC) $(INC_DIRS) $(FLAGS) -o test_33_strcpy_b.bin test_33_strcpy_b.c $(LOG); \
 	if [ $$? -eq 0 ]; then \
 		echo "test_33_strcpy_b: PASS"; \
 	else \
 		echo "test_33_strcpy_b: *FAIL*"; \
+	fi
+
+# should detect the issue
+test_34_strlen_b:
+	$(CC) $(INC_DIRS) $(FLAGS) -fno-delete-null-pointer-checks -o test_34_strlen_b.bin test_34_strlen_b.c $(LOG); \
+	if [ $$? -eq 0 ]; then \
+		echo "test_33_strcpy_b: *FAIL*"; \
+	else \
+		echo "test_33_strcpy_b: PASS"; \
 	fi
 
 clean:
